# Docker Compose for deploying both Backend and MCP on the same server
version: '3.8'

services:
  wildeditor-backend:
    image: ghcr.io/luminarimud/wildeditor-backend:latest
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8000
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - WILDEDITOR_API_KEY=${WILDEDITOR_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,https://wildedit.luminarimud.com}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wildeditor

  wildeditor-mcp:
    image: ghcr.io/luminarimud/wildeditor-mcp:latest
    ports:
      - "${MCP_PORT:-8001}:8001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - WILDEDITOR_MCP_PORT=8001
      - WILDEDITOR_BACKEND_URL=http://wildeditor-backend:8000  # Internal container communication
      - WILDEDITOR_API_KEY=${WILDEDITOR_API_KEY}
      - WILDEDITOR_MCP_KEY=${WILDEDITOR_MCP_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      wildeditor-backend:
        condition: service_healthy
    networks:
      - wildeditor

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - wildeditor-backend
      - wildeditor-mcp
    networks:
      - wildeditor
    restart: unless-stopped

networks:
  wildeditor:
    driver: bridge
